# Generated by Django 2.0.1 on 2018-01-12 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMSAdmin', '0002_auto_20180112_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpolicycomprehensive',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customerpolicytp',
            name='name',
        ),
        migrations.AddField(
            model_name='customerpolicycomprehensive',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='IMSAdmin.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpolicytp',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='IMSAdmin.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='logo',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
